### PR TITLE
Handling CREATED state in gateway complete

### PR DESCRIPTION
**Pull request by mikoczy**

### CODE REVIEW

**Comment by rootpd** [comment]
Just out of curiosity. What actually confirms the payment if it was not settled at the time of the confirmation? Don't we need some kind of webhook or external confirmation?

**Comment by mikoczy** [comment]
when the payment is confirmed (or the payment status changes in any way), gopay makes a request to the notification endpoint.. the payment can be only handled there - the user can ignore/close the payment window, which leaves the payment in created state, so we need to wait for a notification..

**Comment by rootpd** [comment]
Oh, right 🤦 . I put this to the internal review and I'll update the issue once is merged / released. Thanks for the changes.

**Comment by rootpd** [comment]
Merged via https://github.com/remp2020/crm-gopay-module/commit/2f1f2ad346482cde57ab737eaf9f148bd68cb1ed, I expect the new version to be tagged sometime next week.

**Pull request closed without merging**
